# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""add alerting system

Revision ID: 28bef5bec0ee
Revises: e6d683ebc878
Create Date: 2026-04-29 10:04:04.377854+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '28bef5bec0ee'
down_revision = 'e6d683ebc878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'RETRYING', 'SENT', 'FAILED', 'SUPPRESSED', name='notificationstatus').create(op.get_bind())
    sa.Enum('EMAIL', 'WEBHOOK', 'SLACK', 'PAGERDUTY', name='alertintegrationkind').create(op.get_bind())
    sa.Enum('OK', 'TRIGGERED', 'RECOVERED', 'ERROR', name='alerthistorystatus').create(op.get_bind())
    sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity').create(op.get_bind())
    sa.Enum('THRESHOLD', 'RATE_OF_CHANGE', 'COMPOSITE', name='alertrulekind').create(op.get_bind())
    sa.Enum('TVL', 'NUMBER_OF_NODES', 'NUMBER_OF_SOFTWARE_CLIENTS', 'GAS_PRICE', 'TRANSACTIONS_PER_SECOND', 'BLOCKS_PER_SECOND', 'DELAY_ON_UPGRADE', 'EXIT_WINDOW', 'STATE_VALIDATION', 'UPGRADE_TRANSPARENCY', 'SLASHING_BEHAVIOR', 'LAST_RELEASE_DATE', 'VITALIK_ROLLUP_MILESTONE', 'TOTAL_AMOUNT_OF_STAKES', 'NAKAMOTO_LIVENESS_COEFFICIENT', 'NAKAMOTO_SAFETY_COEFFICIENT', 'HHI', 'RENYI_ENTROPY_ALPHA_0', 'RENYI_ENTROPY_ALPHA_1', 'RENYI_ENTROPY_ALPHA_2', 'RENYI_ENTROPY_ALPHA_INF', 'SHAPLEY_TOP_VALUE', 'SHAPLEY_SECOND_VALUE', 'SHAPLEY_THIRD_VALUE', 'USDC_INFLOW', 'USDC_OUTFLOW', 'USDC_UNIQUE_ADDRESSES', 'USDC_TRANSACTION_COUNT', 'USDC_TOTAL_SUPPLY', 'USDT0_TOTAL_AMOUNT_TRANSFERS', 'USDT0_INFLOW', 'USDT0_OUTFLOW', 'USDT0_UNIQUE_ADDRESSES', 'USDT0_TRANSACTION_COUNT', 'USDT0_TVL', 'ETH_FINALITY', 'SOL_FINALITY', 'ARB_FINALITY', 'INK_FINALITY', 'POLYGON_FINALITY', 'UNICHAIN_FINALITY', 'BASE_FINALITY', 'ETH_WETH_INFLOW', 'ETH_WETH_OUTFLOW', 'ETH_WETH_TOTAL_SUPPLY', 'ETH_USDE_TOTAL_SUPPLY', 'ETH_USDE_TRANSFER_COUNT', 'ETH_USDE_UNIQUE_ADDRESSES', 'ETH_USDE_VOLUME', 'ETH_AAVE_TOTAL_SUPPLY', 'ETH_AAVE_TRANSFER_COUNT', 'ETH_AAVE_UNIQUE_ADDRESSES', 'ETH_AAVE_VOLUME', 'ETH_UNI_TOTAL_SUPPLY', 'ETH_UNI_TRANSFER_COUNT', 'ETH_UNI_UNIQUE_ADDRESSES', 'ETH_UNI_VOLUME', 'UNIQUE_ADDRESSES', 'TRANSACTION_COUNT', 'VOTING_DELEGATION_LAYER_COEFFICIENT', 'UPGRADE_AUTHORITY_COEFFICIENT', 'EMERGENCY_POWERS_BYPASS_RISK', 'BASE_GOVERNANCE_EXECUTION', 'SOLANA_GOVERNANCE_PROPOSALS', 'ETH_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_EXECUTION', 'ARB_GOVERNANCE_EMERGENCY', 'DECENTRALIZATION_COMBINED', 'TIME_TO_FINALITY_SOFT', name='metrictype').create(op.get_bind())
    op.create_table('alert',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=True),
    sa.Column('token', postgresql.ENUM('WETH', 'USDE', 'AAVE', 'UNI', 'USDC', 'USDT0', 'AUSDC', 'CUSDC', 'LINK', 'STETH', 'WSTETH', name='tokentype', create_type=False), nullable=True),
    sa.Column('metric_type', postgresql.ENUM('TVL', 'NUMBER_OF_NODES', 'NUMBER_OF_SOFTWARE_CLIENTS', 'GAS_PRICE', 'TRANSACTIONS_PER_SECOND', 'BLOCKS_PER_SECOND', 'DELAY_ON_UPGRADE', 'EXIT_WINDOW', 'STATE_VALIDATION', 'UPGRADE_TRANSPARENCY', 'SLASHING_BEHAVIOR', 'LAST_RELEASE_DATE', 'VITALIK_ROLLUP_MILESTONE', 'TOTAL_AMOUNT_OF_STAKES', 'NAKAMOTO_LIVENESS_COEFFICIENT', 'NAKAMOTO_SAFETY_COEFFICIENT', 'HHI', 'RENYI_ENTROPY_ALPHA_0', 'RENYI_ENTROPY_ALPHA_1', 'RENYI_ENTROPY_ALPHA_2', 'RENYI_ENTROPY_ALPHA_INF', 'SHAPLEY_TOP_VALUE', 'SHAPLEY_SECOND_VALUE', 'SHAPLEY_THIRD_VALUE', 'USDC_INFLOW', 'USDC_OUTFLOW', 'USDC_UNIQUE_ADDRESSES', 'USDC_TRANSACTION_COUNT', 'USDC_TOTAL_SUPPLY', 'USDT0_TOTAL_AMOUNT_TRANSFERS', 'USDT0_INFLOW', 'USDT0_OUTFLOW', 'USDT0_UNIQUE_ADDRESSES', 'USDT0_TRANSACTION_COUNT', 'USDT0_TVL', 'ETH_FINALITY', 'SOL_FINALITY', 'ARB_FINALITY', 'INK_FINALITY', 'POLYGON_FINALITY', 'UNICHAIN_FINALITY', 'BASE_FINALITY', 'ETH_WETH_INFLOW', 'ETH_WETH_OUTFLOW', 'ETH_WETH_TOTAL_SUPPLY', 'ETH_USDE_TOTAL_SUPPLY', 'ETH_USDE_TRANSFER_COUNT', 'ETH_USDE_UNIQUE_ADDRESSES', 'ETH_USDE_VOLUME', 'ETH_AAVE_TOTAL_SUPPLY', 'ETH_AAVE_TRANSFER_COUNT', 'ETH_AAVE_UNIQUE_ADDRESSES', 'ETH_AAVE_VOLUME', 'ETH_UNI_TOTAL_SUPPLY', 'ETH_UNI_TRANSFER_COUNT', 'ETH_UNI_UNIQUE_ADDRESSES', 'ETH_UNI_VOLUME', 'UNIQUE_ADDRESSES', 'TRANSACTION_COUNT', 'VOTING_DELEGATION_LAYER_COEFFICIENT', 'UPGRADE_AUTHORITY_COEFFICIENT', 'EMERGENCY_POWERS_BYPASS_RISK', 'BASE_GOVERNANCE_EXECUTION', 'SOLANA_GOVERNANCE_PROPOSALS', 'ETH_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_EXECUTION', 'ARB_GOVERNANCE_EMERGENCY', 'DECENTRALIZATION_COMBINED', 'TIME_TO_FINALITY_SOFT', name='metrictype', create_type=False), nullable=False),
    sa.Column('rule_kind', postgresql.ENUM('THRESHOLD', 'RATE_OF_CHANGE', 'COMPOSITE', name='alertrulekind', create_type=False), nullable=False),
    sa.Column('rule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alertseverity', create_type=False), server_default='WARNING', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('updated_by', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('(is_template = true AND team_id IS NULL) OR (is_template = false AND team_id IS NOT NULL)', name=op.f('ck_alert_template_team_xor')),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], name=op.f('fk_alert_created_by_user_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_alert_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user_account.id'], name=op.f('fk_alert_updated_by_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert'))
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index('ix_alert_metric', ['chain', 'token', 'metric_type'], unique=False)
        batch_op.create_index('ix_alert_rule_config_gin', ['rule_config'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_alert_team_enabled', ['team_id', 'is_enabled'], unique=False, postgresql_where=sa.text('is_template = false'))
        batch_op.create_index(batch_op.f('ix_alert_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_alert_template_enabled', ['is_enabled'], unique=False, postgresql_where=sa.text('is_template = true'))

    op.create_table('alert_integration',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('kind', postgresql.ENUM('EMAIL', 'WEBHOOK', 'SLACK', 'PAGERDUTY', name='alertintegrationkind', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.GUID(length=16), nullable=False),
    sa.Column('updated_by', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_account.id'], name=op.f('fk_alert_integration_created_by_user_account'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_alert_integration_team_id_team'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['user_account.id'], name=op.f('fk_alert_integration_updated_by_user_account'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_integration'))
    )
    with op.batch_alter_table('alert_integration', schema=None) as batch_op:
        batch_op.create_index('ix_alert_integration_team', ['team_id'], unique=False)
        batch_op.create_index('uq_alert_integration_primary', ['team_id', 'kind'], unique=True, postgresql_where=sa.text('is_primary = true'))

    op.create_table('alert_history',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('alert_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('status', postgresql.ENUM('OK', 'TRIGGERED', 'RECOVERED', 'ERROR', name='alerthistorystatus', create_type=False), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_alert_history_alert_id_alert'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_alert_history_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_history'))
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index('ix_alert_history_active', ['alert_id'], unique=False, postgresql_where=sa.text("status = 'TRIGGERED'"))
        batch_op.create_index('ix_alert_history_alert_evaluated', ['alert_id', 'evaluated_at'], unique=False)
        batch_op.create_index('ix_alert_history_team_evaluated', ['team_id', 'evaluated_at'], unique=False)

    op.create_table('alert_integration_link',
    sa.Column('alert_id', sa.GUID(length=16), nullable=False),
    sa.Column('integration_id', sa.GUID(length=16), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_alert_integration_link_alert_id_alert'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['alert_integration.id'], name=op.f('fk_alert_integration_link_integration_id_alert_integration'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'integration_id', name=op.f('pk_alert_integration_link'))
    )
    op.create_table('team_alert_override',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('alert_id', sa.GUID(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('integration_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_team_alert_override_alert_id_alert'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['alert_integration.id'], name=op.f('fk_team_alert_override_integration_id_alert_integration'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_team_alert_override_team_id_team'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_alert_override')),
    sa.UniqueConstraint('team_id', 'alert_id', name=op.f('uq_team_alert_override_team_id'))
    )
    op.create_table('notification',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('alert_history_id', sa.GUID(length=16), nullable=False),
    sa.Column('integration_id', sa.GUID(length=16), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RETRYING', 'SENT', 'FAILED', 'SUPPRESSED', name='notificationstatus', create_type=False), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_history_id'], ['alert_history.id'], name=op.f('fk_notification_alert_history_id_alert_history'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['alert_integration.id'], name=op.f('fk_notification_integration_id_alert_integration'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_history', ['alert_history_id'], unique=False)
        batch_op.create_index('ix_notification_pending', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('PENDING', 'RETRYING')"))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_pending', postgresql_where=sa.text("status IN ('PENDING', 'RETRYING')"))
        batch_op.drop_index('ix_notification_history')

    op.drop_table('notification')
    op.drop_table('team_alert_override')
    op.drop_table('alert_integration_link')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_history_team_evaluated')
        batch_op.drop_index('ix_alert_history_alert_evaluated')
        batch_op.drop_index('ix_alert_history_active', postgresql_where=sa.text("status = 'TRIGGERED'"))

    op.drop_table('alert_history')
    with op.batch_alter_table('alert_integration', schema=None) as batch_op:
        batch_op.drop_index('uq_alert_integration_primary', postgresql_where=sa.text('is_primary = true'))
        batch_op.drop_index('ix_alert_integration_team')

    op.drop_table('alert_integration')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_template_enabled', postgresql_where=sa.text('is_template = true'))
        batch_op.drop_index(batch_op.f('ix_alert_team_id'))
        batch_op.drop_index('ix_alert_team_enabled', postgresql_where=sa.text('is_template = false'))
        batch_op.drop_index('ix_alert_rule_config_gin', postgresql_using='gin')
        batch_op.drop_index('ix_alert_metric')

    op.drop_table('alert')
    sa.Enum('TVL', 'NUMBER_OF_NODES', 'NUMBER_OF_SOFTWARE_CLIENTS', 'GAS_PRICE', 'TRANSACTIONS_PER_SECOND', 'BLOCKS_PER_SECOND', 'DELAY_ON_UPGRADE', 'EXIT_WINDOW', 'STATE_VALIDATION', 'UPGRADE_TRANSPARENCY', 'SLASHING_BEHAVIOR', 'LAST_RELEASE_DATE', 'VITALIK_ROLLUP_MILESTONE', 'TOTAL_AMOUNT_OF_STAKES', 'NAKAMOTO_LIVENESS_COEFFICIENT', 'NAKAMOTO_SAFETY_COEFFICIENT', 'HHI', 'RENYI_ENTROPY_ALPHA_0', 'RENYI_ENTROPY_ALPHA_1', 'RENYI_ENTROPY_ALPHA_2', 'RENYI_ENTROPY_ALPHA_INF', 'SHAPLEY_TOP_VALUE', 'SHAPLEY_SECOND_VALUE', 'SHAPLEY_THIRD_VALUE', 'USDC_INFLOW', 'USDC_OUTFLOW', 'USDC_UNIQUE_ADDRESSES', 'USDC_TRANSACTION_COUNT', 'USDC_TOTAL_SUPPLY', 'USDT0_TOTAL_AMOUNT_TRANSFERS', 'USDT0_INFLOW', 'USDT0_OUTFLOW', 'USDT0_UNIQUE_ADDRESSES', 'USDT0_TRANSACTION_COUNT', 'USDT0_TVL', 'ETH_FINALITY', 'SOL_FINALITY', 'ARB_FINALITY', 'INK_FINALITY', 'POLYGON_FINALITY', 'UNICHAIN_FINALITY', 'BASE_FINALITY', 'ETH_WETH_INFLOW', 'ETH_WETH_OUTFLOW', 'ETH_WETH_TOTAL_SUPPLY', 'ETH_USDE_TOTAL_SUPPLY', 'ETH_USDE_TRANSFER_COUNT', 'ETH_USDE_UNIQUE_ADDRESSES', 'ETH_USDE_VOLUME', 'ETH_AAVE_TOTAL_SUPPLY', 'ETH_AAVE_TRANSFER_COUNT', 'ETH_AAVE_UNIQUE_ADDRESSES', 'ETH_AAVE_VOLUME', 'ETH_UNI_TOTAL_SUPPLY', 'ETH_UNI_TRANSFER_COUNT', 'ETH_UNI_UNIQUE_ADDRESSES', 'ETH_UNI_VOLUME', 'UNIQUE_ADDRESSES', 'TRANSACTION_COUNT', 'VOTING_DELEGATION_LAYER_COEFFICIENT', 'UPGRADE_AUTHORITY_COEFFICIENT', 'EMERGENCY_POWERS_BYPASS_RISK', 'BASE_GOVERNANCE_EXECUTION', 'SOLANA_GOVERNANCE_PROPOSALS', 'ETH_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_EXECUTION', 'ARB_GOVERNANCE_EMERGENCY', 'DECENTRALIZATION_COMBINED', 'TIME_TO_FINALITY_SOFT', name='metrictype').drop(op.get_bind())
    sa.Enum('THRESHOLD', 'RATE_OF_CHANGE', 'COMPOSITE', name='alertrulekind').drop(op.get_bind())
    sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity').drop(op.get_bind())
    sa.Enum('OK', 'TRIGGERED', 'RECOVERED', 'ERROR', name='alerthistorystatus').drop(op.get_bind())
    sa.Enum('EMAIL', 'WEBHOOK', 'SLACK', 'PAGERDUTY', name='alertintegrationkind').drop(op.get_bind())
    sa.Enum('PENDING', 'RETRYING', 'SENT', 'FAILED', 'SUPPRESSED', name='notificationstatus').drop(op.get_bind())
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
