# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""Add automatic metrics

Revision ID: 6206be1fec90
Revises: c42012a3aced
Create Date: 2026-04-24 14:18:55.041264+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '6206be1fec90'
down_revision = 'c42012a3aced'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decentralization',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('total_amount_of_stakes', sa.Float(), nullable=False),
    sa.Column('number_of_nodes', sa.BigInteger(), nullable=False),
    sa.Column('nakamoto_liveness_coefficient', sa.BigInteger(), nullable=False),
    sa.Column('nakamoto_safety_coefficient', sa.BigInteger(), nullable=False),
    sa.Column('hhi', sa.Float(), nullable=False),
    sa.Column('shapley_top_value', sa.Float(), nullable=False),
    sa.Column('shapley_second_value', sa.Float(), nullable=False),
    sa.Column('shapley_third_value', sa.Float(), nullable=False),
    sa.Column('renyi_entropy_alpha_0', sa.Float(), nullable=False),
    sa.Column('renyi_entropy_alpha_1', sa.Float(), nullable=False),
    sa.Column('renyi_entropy_alpha_2', sa.Float(), nullable=False),
    sa.Column('renyi_entropy_alpha_inf', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decentralization'))
    )
    with op.batch_alter_table('decentralization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decentralization_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_decentralization_chain_created_at', ['chain', 'created_at'], unique=False)

    op.create_table('throughput',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('gas_price', sa.Float(), nullable=False),
    sa.Column('transactions_per_second', sa.Float(), nullable=False),
    sa.Column('blocks_per_second', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_throughput'))
    )
    with op.batch_alter_table('throughput', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_throughput_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_throughput_chain_created_at', ['chain', 'created_at'], unique=False)

    op.create_table('time_to_finality',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('soft_finality_seconds', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_to_finality'))
    )
    with op.batch_alter_table('time_to_finality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_to_finality_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_time_to_finality_chain_created_at', ['chain', 'created_at'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_to_finality', schema=None) as batch_op:
        batch_op.drop_index('ix_time_to_finality_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_time_to_finality_chain'))

    op.drop_table('time_to_finality')
    with op.batch_alter_table('throughput', schema=None) as batch_op:
        batch_op.drop_index('ix_throughput_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_throughput_chain'))

    op.drop_table('throughput')
    with op.batch_alter_table('decentralization', schema=None) as batch_op:
        batch_op.drop_index('ix_decentralization_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_decentralization_chain'))

    op.drop_table('decentralization')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
