# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""Make user_favorite_metric uniqueness partial

Revision ID: deb231764c7d
Revises: 6002068eb484
Create Date: 2026-05-12 14:23:28.731373+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'deb231764c7d'
down_revision = '6002068eb484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_metric', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_favorite_metric_auto'), type_='unique')
        batch_op.create_index('uq_user_favorite_metric_auto', ['user_id', 'metric_type', 'chain', 'token'], unique=True, postgresql_where=sa.text('manual_metric_id IS NULL'), postgresql_nulls_not_distinct=True)
        batch_op.drop_constraint(batch_op.f('uq_user_favorite_metric_manual'), type_='unique')
        batch_op.create_index('uq_user_favorite_metric_manual', ['user_id', 'manual_metric_id'], unique=True, postgresql_where=sa.text('manual_metric_id IS NOT NULL'))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_metric', schema=None) as batch_op:
        batch_op.drop_index('uq_user_favorite_metric_manual', postgresql_where=sa.text('manual_metric_id IS NOT NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_user_favorite_metric_manual'), ['user_id', 'manual_metric_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_index('uq_user_favorite_metric_auto', postgresql_where=sa.text('manual_metric_id IS NULL'), postgresql_nulls_not_distinct=True)
        batch_op.create_unique_constraint(batch_op.f('uq_user_favorite_metric_auto'), ['user_id', 'metric_type', 'chain', 'token'], postgresql_nulls_not_distinct=True)

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
