# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""Create finality tables

Revision ID: c42012a3aced
Revises: 1f2d9a6c1b3e
Create Date: 2026-04-22 15:15:48.185477+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'c42012a3aced'
down_revision = '1f2d9a6c1b3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype').create(op.get_bind())
    op.create_table('finality_ethereum',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('head_height', sa.BigInteger(), nullable=False),
    sa.Column('finalized_height', sa.BigInteger(), nullable=False),
    sa.Column('safe_height', sa.BigInteger(), nullable=False),
    sa.Column('justified_epoch', sa.BigInteger(), nullable=False),
    sa.Column('finalized_epoch', sa.BigInteger(), nullable=False),
    sa.Column('justified_finalized_gap', sa.BigInteger(), nullable=False),
    sa.Column('time_since_finality_advance', sa.Float(), nullable=False),
    sa.Column('head_to_finalized_time', sa.BigInteger(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finality_ethereum'))
    )
    with op.batch_alter_table('finality_ethereum', schema=None) as batch_op:
        batch_op.create_index('ix_finality_ethereum_created_at', ['created_at'], unique=False)

    op.create_table('finality_evm_l2',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('latest_height', sa.BigInteger(), nullable=False),
    sa.Column('safe_height', sa.BigInteger(), nullable=False),
    sa.Column('finalized_height', sa.BigInteger(), nullable=False),
    sa.Column('latest_to_safe_blocks', sa.BigInteger(), nullable=False),
    sa.Column('safe_to_finalized_blocks', sa.BigInteger(), nullable=False),
    sa.Column('time_since_last_head', sa.Float(), nullable=False),
    sa.Column('height_correlation', sa.BigInteger(), nullable=True),
    sa.Column('time_to_hard_finality', sa.BigInteger(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finality_evm_l2'))
    )
    with op.batch_alter_table('finality_evm_l2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finality_evm_l2_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_finality_evm_l2_chain_created_at', ['chain', 'created_at'], unique=False)

    op.create_table('finality_op_stack',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('unsafe_height', sa.BigInteger(), nullable=False),
    sa.Column('safe_height', sa.BigInteger(), nullable=False),
    sa.Column('finalized_height', sa.BigInteger(), nullable=False),
    sa.Column('unsafe_to_safe_blocks', sa.BigInteger(), nullable=False),
    sa.Column('safe_to_finalized_blocks', sa.BigInteger(), nullable=False),
    sa.Column('time_since_last_unsafe', sa.Float(), nullable=False),
    sa.Column('height_correlation', sa.BigInteger(), nullable=False),
    sa.Column('time_to_hard_finality', sa.BigInteger(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finality_op_stack'))
    )
    with op.batch_alter_table('finality_op_stack', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finality_op_stack_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_finality_op_stack_chain_created_at', ['chain', 'created_at'], unique=False)

    op.create_table('finality_polygon',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('latest_height', sa.BigInteger(), nullable=False),
    sa.Column('finalized_height', sa.BigInteger(), nullable=False),
    sa.Column('latest_to_finalized_blocks', sa.BigInteger(), nullable=False),
    sa.Column('time_since_last_head', sa.Float(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finality_polygon'))
    )
    with op.batch_alter_table('finality_polygon', schema=None) as batch_op:
        batch_op.create_index('ix_finality_polygon_created_at', ['created_at'], unique=False)

    op.create_table('finality_solana',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('processed_slot', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_slot', sa.BigInteger(), nullable=False),
    sa.Column('finalized_slot', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_finalized_gap', sa.BigInteger(), nullable=False),
    sa.Column('processed_confirmed_gap', sa.BigInteger(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finality_solana'))
    )
    with op.batch_alter_table('finality_solana', schema=None) as batch_op:
        batch_op.create_index('ix_finality_solana_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tracks administrative actions for auditing and compliance',
        existing_comment=None
    )

    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tokens for email verification, password reset, etc.',
        existing_comment=None
    )

    with op.batch_alter_table('session_store', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               nullable=False)

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_table_comment(
        'User accounts for application access',
        existing_comment=None
    )

    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Registered OAUTH2 Accounts for Users',
        existing_comment=None
    )

    with op.batch_alter_table('user_account_role', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Links a user to a specific role.',
        existing_comment=None
    )

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account_role', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Links a user to a specific role.'
    )

    with op.batch_alter_table('user_account_oauth', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Registered OAUTH2 Accounts for Users'
    )

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='User accounts for application access'
    )

    with op.batch_alter_table('session_store', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               nullable=True)

    with op.batch_alter_table('email_token', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Tokens for email verification, password reset, etc.'
    )

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Tracks administrative actions for auditing and compliance'
    )

    with op.batch_alter_table('finality_solana', schema=None) as batch_op:
        batch_op.drop_index('ix_finality_solana_created_at')

    op.drop_table('finality_solana')
    with op.batch_alter_table('finality_polygon', schema=None) as batch_op:
        batch_op.drop_index('ix_finality_polygon_created_at')

    op.drop_table('finality_polygon')
    with op.batch_alter_table('finality_op_stack', schema=None) as batch_op:
        batch_op.drop_index('ix_finality_op_stack_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_finality_op_stack_chain'))

    op.drop_table('finality_op_stack')
    with op.batch_alter_table('finality_evm_l2', schema=None) as batch_op:
        batch_op.drop_index('ix_finality_evm_l2_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_finality_evm_l2_chain'))

    op.drop_table('finality_evm_l2')
    with op.batch_alter_table('finality_ethereum', schema=None) as batch_op:
        batch_op.drop_index('ix_finality_ethereum_created_at')

    op.drop_table('finality_ethereum')
    sa.Enum('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype').drop(op.get_bind())
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
