# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""add decentralization operator snapshot

Revision ID: bedb22e90a81
Revises: 24ced8d21233
Create Date: 2026-05-28 10:24:28.337755+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'bedb22e90a81'
down_revision = '24ced8d21233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decentralization_operator_snapshot',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('entity_nakamoto_liveness', sa.BigInteger(), nullable=False),
    sa.Column('entity_nakamoto_safety', sa.BigInteger(), nullable=False),
    sa.Column('entity_count', sa.BigInteger(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('top_operators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decentralization_operator_snapshot'))
    )
    with op.batch_alter_table('decentralization_operator_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_decentralization_operator_chain_created_at', ['chain', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decentralization_operator_snapshot_chain'), ['chain'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decentralization_operator_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decentralization_operator_snapshot_chain'))
        batch_op.drop_index('ix_decentralization_operator_chain_created_at')

    op.drop_table('decentralization_operator_snapshot')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
