# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""Add user_favorite_metric table

Revision ID: 6002068eb484
Revises: a3f1c8e209d4
Create Date: 2026-05-12 13:29:46.116783+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '6002068eb484'
down_revision = 'a3f1c8e209d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_metric',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('metric_type', postgresql.ENUM('TVL', 'NUMBER_OF_NODES', 'NUMBER_OF_SOFTWARE_CLIENTS', 'GAS_PRICE', 'TRANSACTIONS_PER_SECOND', 'BLOCKS_PER_SECOND', 'DELAY_ON_UPGRADE', 'EXIT_WINDOW', 'STATE_VALIDATION', 'UPGRADE_TRANSPARENCY', 'SLASHING_BEHAVIOR', 'LAST_RELEASE_DATE', 'VITALIK_ROLLUP_MILESTONE', 'TOTAL_AMOUNT_OF_STAKES', 'NAKAMOTO_LIVENESS_COEFFICIENT', 'NAKAMOTO_SAFETY_COEFFICIENT', 'HHI', 'RENYI_ENTROPY_ALPHA_0', 'RENYI_ENTROPY_ALPHA_1', 'RENYI_ENTROPY_ALPHA_2', 'RENYI_ENTROPY_ALPHA_INF', 'SHAPLEY_TOP_VALUE', 'SHAPLEY_SECOND_VALUE', 'SHAPLEY_THIRD_VALUE', 'USDC_INFLOW', 'USDC_OUTFLOW', 'USDC_UNIQUE_ADDRESSES', 'USDC_TRANSACTION_COUNT', 'USDC_TOTAL_SUPPLY', 'USDT0_TOTAL_AMOUNT_TRANSFERS', 'USDT0_INFLOW', 'USDT0_OUTFLOW', 'USDT0_UNIQUE_ADDRESSES', 'USDT0_TRANSACTION_COUNT', 'USDT0_TVL', 'ETH_FINALITY', 'SOL_FINALITY', 'ARB_FINALITY', 'INK_FINALITY', 'POLYGON_FINALITY', 'UNICHAIN_FINALITY', 'BASE_FINALITY', 'ETH_WETH_INFLOW', 'ETH_WETH_OUTFLOW', 'ETH_WETH_TOTAL_SUPPLY', 'ETH_USDE_TOTAL_SUPPLY', 'ETH_USDE_TRANSFER_COUNT', 'ETH_USDE_UNIQUE_ADDRESSES', 'ETH_USDE_VOLUME', 'ETH_AAVE_TOTAL_SUPPLY', 'ETH_AAVE_TRANSFER_COUNT', 'ETH_AAVE_UNIQUE_ADDRESSES', 'ETH_AAVE_VOLUME', 'ETH_UNI_TOTAL_SUPPLY', 'ETH_UNI_TRANSFER_COUNT', 'ETH_UNI_UNIQUE_ADDRESSES', 'ETH_UNI_VOLUME', 'UNIQUE_ADDRESSES', 'TRANSACTION_COUNT', 'VOTING_DELEGATION_LAYER_COEFFICIENT', 'UPGRADE_AUTHORITY_COEFFICIENT', 'EMERGENCY_POWERS_BYPASS_RISK', 'BASE_GOVERNANCE_EXECUTION', 'SOLANA_GOVERNANCE_PROPOSALS', 'ETH_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_EXECUTION', 'ARB_GOVERNANCE_EMERGENCY', 'DECENTRALIZATION_COMBINED', 'TIME_TO_FINALITY_SOFT', name='metrictype', create_type=False), nullable=True),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=True),
    sa.Column('token', postgresql.ENUM('WETH', 'USDE', 'AAVE', 'UNI', 'USDC', 'USDT0', 'AUSDC', 'CUSDC', 'LINK', 'STETH', 'WSTETH', name='tokentype', create_type=False), nullable=True),
    sa.Column('manual_metric_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('(metric_type IS NOT NULL AND manual_metric_id IS NULL) OR (metric_type IS NULL AND manual_metric_id IS NOT NULL)', name=op.f('ck_user_favorite_metric_ck_user_favorite_metric_target_xor')),
    sa.ForeignKeyConstraint(['manual_metric_id'], ['manual_metric.id'], name=op.f('fk_user_favorite_metric_manual_metric_id_manual_metric'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_favorite_metric_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_favorite_metric')),
    sa.UniqueConstraint('user_id', 'manual_metric_id', name='uq_user_favorite_metric_manual'),
    sa.UniqueConstraint('user_id', 'metric_type', 'chain', 'token', name='uq_user_favorite_metric_auto', postgresql_nulls_not_distinct=True)
    )
    with op.batch_alter_table('user_favorite_metric', schema=None) as batch_op:
        batch_op.create_index('ix_user_favorite_metric_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_user_favorite_metric_user_id')

    op.drop_table('user_favorite_metric')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
