# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""add_team_id_to_manual_metric

Revision ID: 52a7c181a97a
Revises: deb231764c7d
Create Date: 2026-05-27 07:24:17.129037+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '52a7c181a97a'
down_revision = 'deb231764c7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.GUID(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_manual_metric_team_id'), ['team_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_manual_metric_team_id_team'), 'team', ['team_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_metric', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_manual_metric_team_id_team'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_manual_metric_team_id'))
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
