# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""oidc multi tenant sso foundation

Revision ID: 6847e91bc66b
Revises: 8abadb330266
Create Date: 2026-06-03 04:55:14.938644+00:00

"""

import warnings

import sqlalchemy as sa
from advanced_alchemy.types import (
    GUID,
    ORA_JSONB,
    DateTimeUTC,
    EncryptedString,
    EncryptedText,
    FernetBackend,
    PasswordHash,
    StoredObject,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

__all__ = [
    "data_downgrades",
    "data_upgrades",
    "downgrade",
    "schema_downgrades",
    "schema_upgrades",
    "upgrade",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = "6847e91bc66b"
down_revision = "8abadb330266"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """Schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_attempt_log",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "ip",
            sa.String(length=45),
            nullable=False,
            comment="IPv4 or IPv6 source address",
        ),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the attempt arrived",
        ),
        sa.Column(
            "path",
            sa.String(length=255),
            nullable=False,
            comment="Request path (e.g., '/auth/login') for forensic correlation",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_attempt_log")),
    )
    with op.batch_alter_table("auth_attempt_log", schema=None) as batch_op:
        batch_op.create_index(
            "ix_auth_attempt_log_ip_attempted_at", ["ip", "attempted_at"], unique=False
        )

    op.create_table(
        "mfa_attempt",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=True),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="HMAC-SHA-256 of the cookie token",
        ),
        sa.Column(
            "webauthn_challenge",
            sa.LargeBinary(),
            nullable=True,
            comment="32 random bytes; NULL for TOTP/recovery-only attempts",
        ),
        sa.Column(
            "expires_at",
            sa.DateTimeUTC(timezone=True),
            nullable=False,
            comment="now() + 5 minutes at insert",
        ),
        sa.Column(
            "consumed_at",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Set atomically on the first verify POST (success or fail)",
        ),
        sa.Column(
            "outcome",
            sa.String(length=16),
            nullable=True,
            comment="'success' | 'fail' | 'expired'",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_mfa_attempt_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mfa_attempt")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_mfa_attempt_token_hash")),
    )
    with op.batch_alter_table("mfa_attempt", schema=None) as batch_op:
        batch_op.create_index("ix_mfa_attempt_token_hash", ["token_hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_mfa_attempt_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "operator_audit",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "actor_user_id",
            sa.GUID(length=16),
            nullable=False,
            comment="Operator who performed the action (RESTRICT blocks deletion)",
        ),
        sa.Column(
            "actor_session_id",
            sa.String(length=128),
            nullable=False,
            comment="Session ID of the actor for forensic tracing",
        ),
        sa.Column(
            "actor_ip",
            sa.String(length=45),
            nullable=False,
            comment="Source IP of the action",
        ),
        sa.Column(
            "action",
            sa.String(length=64),
            nullable=False,
            comment="Action identifier (e.g., 'force_unlock', 'reset_mfa_only')",
        ),
        sa.Column(
            "target_team_id",
            sa.GUID(length=16),
            nullable=True,
            comment="Target team; nulled on team deletion (audit survives)",
        ),
        sa.Column(
            "target_user_id",
            sa.GUID(length=16),
            nullable=True,
            comment="Target user; nulled on user deletion (audit survives)",
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Action-specific context (provider, role change, etc.). Captures enough that the row is meaningful even after FKs are nulled. Never include secrets.",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user_account.id"],
            name=op.f("fk_operator_audit_actor_user_id_user_account"),
            ondelete="restrict",
        ),
        sa.ForeignKeyConstraint(
            ["target_team_id"],
            ["team.id"],
            name=op.f("fk_operator_audit_target_team_id_team"),
            ondelete="set null",
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["user_account.id"],
            name=op.f("fk_operator_audit_target_user_id_user_account"),
            ondelete="set null",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_audit")),
    )
    with op.batch_alter_table("operator_audit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_operator_audit_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_operator_audit_actor_user_id"),
            ["actor_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_operator_audit_target_team_id"),
            ["target_team_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_operator_audit_target_user_id"),
            ["target_user_id"],
            unique=False,
        )

    op.create_table(
        "pending_oidc_link",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("target_user_id", sa.GUID(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="HMAC-SHA-256 of the cookie token",
        ),
        sa.Column(
            "expires_at",
            sa.DateTimeUTC(timezone=True),
            nullable=False,
            comment="now() + 10 minutes at insert",
        ),
        sa.Column(
            "consumed_at",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Set atomically on successful link-confirm",
        ),
        sa.Column(
            "failed_attempts",
            sa.Integer(),
            nullable=False,
            comment="Wrong-password attempts at /auth/link-confirm",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["user_account.id"],
            name=op.f("fk_pending_oidc_link_target_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_oidc_link")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_pending_oidc_link_token_hash")),
    )
    with op.batch_alter_table("pending_oidc_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pending_oidc_link_target_user_id"),
            ["target_user_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_pending_oidc_link_token_hash", ["token_hash"], unique=False
        )

    op.create_table(
        "pending_provider_switch",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("target_user_id", sa.GUID(length=16), nullable=False),
        sa.Column("source_provider", sa.String(length=32), nullable=False),
        sa.Column("source_subject", sa.String(length=255), nullable=False),
        sa.Column("source_email", sa.String(length=320), nullable=False),
        sa.Column("target_provider", sa.String(length=32), nullable=False),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="HMAC-SHA-256 of the cookie token",
        ),
        sa.Column(
            "expires_at",
            sa.DateTimeUTC(timezone=True),
            nullable=False,
            comment="now() + 10 minutes at insert",
        ),
        sa.Column(
            "consumed_at",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Set atomically on successful target-provider verification",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["user_account.id"],
            name=op.f("fk_pending_provider_switch_target_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pending_provider_switch")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_pending_provider_switch_token_hash")
        ),
    )
    with op.batch_alter_table("pending_provider_switch", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pending_provider_switch_target_user_id"),
            ["target_user_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_pending_provider_switch_token_hash", ["token_hash"], unique=False
        )

    op.create_table(
        "user_lockout",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "ip",
            sa.String(length=45),
            nullable=False,
            comment="IPv4 or IPv6 address of the failed attempt source",
        ),
        sa.Column(
            "failed_count",
            sa.Integer(),
            nullable=False,
            comment="Failures in the current window",
        ),
        sa.Column(
            "first_failed_at",
            sa.DateTimeUTC(timezone=True),
            nullable=False,
            comment="Timestamp of the first failure in the current window",
        ),
        sa.Column(
            "locked_until",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Lockout expiry; NULL means not currently locked",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_lockout_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_lockout")),
        sa.UniqueConstraint("user_id", "ip", name="uq_user_lockout_user_ip"),
    )
    with op.batch_alter_table("user_lockout", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_lockout_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_passkey",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "credential_id",
            sa.LargeBinary(),
            nullable=False,
            comment="WebAuthn credential ID — globally unique",
        ),
        sa.Column(
            "public_key",
            sa.LargeBinary(),
            nullable=False,
            comment="Authenticator public key (CBOR-encoded)",
        ),
        sa.Column(
            "sign_count",
            sa.Integer(),
            nullable=False,
            comment="Last observed signature counter (anti-clone defense)",
        ),
        sa.Column(
            "aaguid",
            sa.String(length=64),
            nullable=True,
            comment="Authenticator AAGUID (model identifier)",
        ),
        sa.Column(
            "transports",
            sa.String(length=128),
            nullable=True,
            comment="Comma-separated authenticator transports (usb,nfc,ble,internal)",
        ),
        sa.Column(
            "device_name",
            sa.String(length=128),
            nullable=False,
            comment="User-supplied label (e.g., 'MacBook Touch ID')",
        ),
        sa.Column("last_used_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_passkey_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_passkey")),
        sa.UniqueConstraint(
            "credential_id", name=op.f("uq_user_passkey_credential_id")
        ),
    )
    with op.batch_alter_table("user_passkey", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_passkey_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_password_reset_token",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="HMAC-SHA-256 of the reset token",
        ),
        sa.Column(
            "expires_at",
            sa.DateTimeUTC(timezone=True),
            nullable=False,
            comment="now() + 1 hour at insert",
        ),
        sa.Column(
            "consumed_at",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Set atomically with the User.hashed_password update",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_password_reset_token_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_password_reset_token")),
        sa.UniqueConstraint(
            "token_hash", name=op.f("uq_user_password_reset_token_token_hash")
        ),
    )
    with op.batch_alter_table("user_password_reset_token", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_password_reset_token_token_hash", ["token_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_password_reset_token_user_id"),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "user_recovery_code",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "code_hash",
            sa.String(length=255),
            nullable=False,
            comment="argon2id hash of the recovery code",
        ),
        sa.Column(
            "used_at",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Set atomically by claim_recovery_code_used",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_recovery_code_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_recovery_code")),
    )
    with op.batch_alter_table("user_recovery_code", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_recovery_code_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_unlock_token",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column(
            "token_hash",
            sa.String(length=255),
            nullable=False,
            comment="HMAC-SHA-256 of the unlock token",
        ),
        sa.Column(
            "expires_at",
            sa.DateTimeUTC(timezone=True),
            nullable=False,
            comment="now() + 24 hours at insert",
        ),
        sa.Column(
            "consumed_at",
            sa.DateTimeUTC(timezone=True),
            nullable=True,
            comment="Set atomically on first click; subsequent clicks rejected",
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_unlock_token_user_id_user_account"),
            ondelete="cascade",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_unlock_token")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_unlock_token_token_hash")),
    )
    with op.batch_alter_table("user_unlock_token", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_unlock_token_token_hash", ["token_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_unlock_token_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enforced_provider",
                sa.String(length=32),
                nullable=True,
                comment="'google' | 'microsoft' | 'github' — only this provider may authenticate this team's members. NULL = any configured provider.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "enforced_provider_set_at",
                sa.DateTimeUTC(timezone=True),
                nullable=True,
                comment="When enforced_provider was most recently set/changed; used by the stuck-members admin view to identify members who haven't completed self-migration since the policy changed",
            )
        )
        batch_op.add_column(
            sa.Column(
                "security_contact_email",
                sa.String(length=320),
                nullable=True,
                comment="Customer's nominated security contact for operator-action and out-of-domain-provision fan-out alerts",
            )
        )
        batch_op.add_column(
            sa.Column(
                "allowed_email_domains",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default="[]",
                nullable=False,
                comment="Lowercase email domains team admins may provision without out-of-domain confirmation. Editable by team owners and operator_tenant_admin (not by team admins).",
            )
        )

    with op.batch_alter_table("team_invitation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "kind",
                sa.String(length=32),
                nullable=True,
                comment="Invitation kind (FIRST_TIME_ACTIVATION | CROSS_TEAM_JOIN). NULL for legacy rows pre-dating the OIDC SSO design.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "user_id",
                sa.GUID(length=16),
                nullable=True,
                comment="Pre-provisioned User row this invitation activates. NULL for legacy rows; new-flow invitations always set this.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "force_provider",
                sa.String(length=32),
                nullable=True,
                comment="If set, the invite link redirects directly to this IdP's OIDC flow. Meaningful only for FIRST_TIME_ACTIVATION.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "revoked_at",
                sa.DateTimeUTC(timezone=True),
                nullable=True,
                comment="When the invitation was revoked (admin reissue, decline, etc.). Distinct from accepted_at; both are exclusive terminal states.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "out_of_domain_override",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
                comment="True iff the admin clicked through the out-of-domain confirmation modal at provisioning time (#2)",
            )
        )
        batch_op.alter_column(
            "token_hash",
            comment="HMAC-SHA-256 hash of invitation token",
            existing_comment="SHA-256 hash of invitation token",
            existing_nullable=True,
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_team_invitation_user_id_user_account"),
            "user_account",
            ["user_id"],
            ["id"],
            ondelete="cascade",
        )

    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "invited_by_user_id",
                sa.GUID(length=16),
                nullable=True,
                comment="Admin who provisioned this user; NULLed if that admin is deleted",
            )
        )
        batch_op.add_column(
            sa.Column(
                "invited_at",
                sa.DateTimeUTC(timezone=True),
                nullable=True,
                comment="When the user was provisioned by an admin",
            )
        )
        batch_op.add_column(
            sa.Column(
                "activated_at",
                sa.DateTimeUTC(timezone=True),
                nullable=True,
                comment="When the user first completed sign-in (password set OR OIDC linked). Once non-NULL, the activation invitation is dead.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_active_lockout",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
                comment="True iff at least one UserLockout row for this user has locked_until > now(). Drives the unlock-email throttle.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "last_unlock_email_at",
                sa.DateTimeUTC(timezone=True),
                nullable=True,
                comment="Most recent unlock-email enqueue timestamp; gates the throttle in enqueue_unlock_email_if_due",
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_account_invited_by_user_id_user_account"),
            "user_account",
            ["invited_by_user_id"],
            ["id"],
            ondelete="set null",
        )

    with op.batch_alter_table("user_account_oauth", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_oauth_provider_subject", ["oauth_name", "account_id"]
        )
        batch_op.create_unique_constraint("uq_oauth_user_singleton", ["user_id"])

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """Schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_account_oauth", schema=None) as batch_op:
        batch_op.drop_constraint("uq_oauth_user_singleton", type_="unique")
        batch_op.drop_constraint("uq_oauth_provider_subject", type_="unique")

    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_account_invited_by_user_id_user_account"),
            type_="foreignkey",
        )
        batch_op.drop_column("last_unlock_email_at")
        batch_op.drop_column("has_active_lockout")
        batch_op.drop_column("activated_at")
        batch_op.drop_column("invited_at")
        batch_op.drop_column("invited_by_user_id")

    with op.batch_alter_table("team_invitation", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_team_invitation_user_id_user_account"), type_="foreignkey"
        )
        batch_op.alter_column(
            "token_hash",
            comment="SHA-256 hash of invitation token",
            existing_comment="HMAC-SHA-256 hash of invitation token",
            existing_nullable=True,
        )
        batch_op.drop_column("out_of_domain_override")
        batch_op.drop_column("revoked_at")
        batch_op.drop_column("force_provider")
        batch_op.drop_column("user_id")
        batch_op.drop_column("kind")

    with op.batch_alter_table("team", schema=None) as batch_op:
        batch_op.drop_column("allowed_email_domains")
        batch_op.drop_column("security_contact_email")
        batch_op.drop_column("enforced_provider_set_at")
        batch_op.drop_column("enforced_provider")

    with op.batch_alter_table("user_unlock_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_unlock_token_user_id"))
        batch_op.drop_index("ix_user_unlock_token_token_hash")

    op.drop_table("user_unlock_token")
    with op.batch_alter_table("user_recovery_code", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_recovery_code_user_id"))

    op.drop_table("user_recovery_code")
    with op.batch_alter_table("user_password_reset_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_password_reset_token_user_id"))
        batch_op.drop_index("ix_user_password_reset_token_token_hash")

    op.drop_table("user_password_reset_token")
    with op.batch_alter_table("user_passkey", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_passkey_user_id"))

    op.drop_table("user_passkey")
    with op.batch_alter_table("user_lockout", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_lockout_user_id"))

    op.drop_table("user_lockout")
    with op.batch_alter_table("pending_provider_switch", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_provider_switch_token_hash")
        batch_op.drop_index(batch_op.f("ix_pending_provider_switch_target_user_id"))

    op.drop_table("pending_provider_switch")
    with op.batch_alter_table("pending_oidc_link", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_oidc_link_token_hash")
        batch_op.drop_index(batch_op.f("ix_pending_oidc_link_target_user_id"))

    op.drop_table("pending_oidc_link")
    with op.batch_alter_table("operator_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_operator_audit_target_user_id"))
        batch_op.drop_index(batch_op.f("ix_operator_audit_target_team_id"))
        batch_op.drop_index(batch_op.f("ix_operator_audit_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_operator_audit_action"))

    op.drop_table("operator_audit")
    with op.batch_alter_table("mfa_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mfa_attempt_user_id"))
        batch_op.drop_index("ix_mfa_attempt_token_hash")

    op.drop_table("mfa_attempt")
    with op.batch_alter_table("auth_attempt_log", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_attempt_log_ip_attempted_at")

    op.drop_table("auth_attempt_log")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
