# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Certora

"""Add TVL, token_activity, governance_event and release tables

Revision ID: b517b723c6be
Revises: 28bef5bec0ee
Create Date: 2026-04-29 14:05:30.076542+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'b517b723c6be'
down_revision = '28bef5bec0ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_event',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_governance_event'))
    )
    with op.batch_alter_table('governance_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_event_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_governance_event_chain_type_created_at', ['chain', 'event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_event_event_type'), ['event_type'], unique=False)

    op.create_table('release',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('released_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release'))
    )
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_release_chain_created_at', ['chain', 'created_at'], unique=False)

    op.create_table('token_activity',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('token', postgresql.ENUM('WETH', 'USDE', 'AAVE', 'UNI', 'USDC', 'USDT0', 'AUSDC', 'CUSDC', 'LINK', 'STETH', 'WSTETH', name='tokentype', create_type=False), nullable=False),
    sa.Column('metric_type', postgresql.ENUM('TVL', 'NUMBER_OF_NODES', 'NUMBER_OF_SOFTWARE_CLIENTS', 'GAS_PRICE', 'TRANSACTIONS_PER_SECOND', 'BLOCKS_PER_SECOND', 'DELAY_ON_UPGRADE', 'EXIT_WINDOW', 'STATE_VALIDATION', 'UPGRADE_TRANSPARENCY', 'SLASHING_BEHAVIOR', 'LAST_RELEASE_DATE', 'VITALIK_ROLLUP_MILESTONE', 'TOTAL_AMOUNT_OF_STAKES', 'NAKAMOTO_LIVENESS_COEFFICIENT', 'NAKAMOTO_SAFETY_COEFFICIENT', 'HHI', 'RENYI_ENTROPY_ALPHA_0', 'RENYI_ENTROPY_ALPHA_1', 'RENYI_ENTROPY_ALPHA_2', 'RENYI_ENTROPY_ALPHA_INF', 'SHAPLEY_TOP_VALUE', 'SHAPLEY_SECOND_VALUE', 'SHAPLEY_THIRD_VALUE', 'USDC_INFLOW', 'USDC_OUTFLOW', 'USDC_UNIQUE_ADDRESSES', 'USDC_TRANSACTION_COUNT', 'USDC_TOTAL_SUPPLY', 'USDT0_TOTAL_AMOUNT_TRANSFERS', 'USDT0_INFLOW', 'USDT0_OUTFLOW', 'USDT0_UNIQUE_ADDRESSES', 'USDT0_TRANSACTION_COUNT', 'USDT0_TVL', 'ETH_FINALITY', 'SOL_FINALITY', 'ARB_FINALITY', 'INK_FINALITY', 'POLYGON_FINALITY', 'UNICHAIN_FINALITY', 'BASE_FINALITY', 'ETH_WETH_INFLOW', 'ETH_WETH_OUTFLOW', 'ETH_WETH_TOTAL_SUPPLY', 'ETH_USDE_TOTAL_SUPPLY', 'ETH_USDE_TRANSFER_COUNT', 'ETH_USDE_UNIQUE_ADDRESSES', 'ETH_USDE_VOLUME', 'ETH_AAVE_TOTAL_SUPPLY', 'ETH_AAVE_TRANSFER_COUNT', 'ETH_AAVE_UNIQUE_ADDRESSES', 'ETH_AAVE_VOLUME', 'ETH_UNI_TOTAL_SUPPLY', 'ETH_UNI_TRANSFER_COUNT', 'ETH_UNI_UNIQUE_ADDRESSES', 'ETH_UNI_VOLUME', 'UNIQUE_ADDRESSES', 'TRANSACTION_COUNT', 'VOTING_DELEGATION_LAYER_COEFFICIENT', 'UPGRADE_AUTHORITY_COEFFICIENT', 'EMERGENCY_POWERS_BYPASS_RISK', 'BASE_GOVERNANCE_EXECUTION', 'SOLANA_GOVERNANCE_PROPOSALS', 'ETH_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_PROPOSALS', 'ARB_GOVERNANCE_EXECUTION', 'ARB_GOVERNANCE_EMERGENCY', 'DECENTRALIZATION_COMBINED', 'TIME_TO_FINALITY_SOFT', name='metrictype', create_type=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_activity'))
    )
    with op.batch_alter_table('token_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_activity_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_token_activity_chain_token_metric_created_at', ['chain', 'token', 'metric_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_activity_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_activity_token'), ['token'], unique=False)

    op.create_table('tvl',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chain', postgresql.ENUM('ARBITRUM', 'ETHEREUM', 'SOLANA', 'BASE', 'INK', 'UNICHAIN', 'POLYGON', 'AVALANCHE_C', 'OPTIMISM', name='chaintype', create_type=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tvl'))
    )
    with op.batch_alter_table('tvl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tvl_chain'), ['chain'], unique=False)
        batch_op.create_index('ix_tvl_chain_created_at', ['chain', 'created_at'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tvl', schema=None) as batch_op:
        batch_op.drop_index('ix_tvl_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_tvl_chain'))

    op.drop_table('tvl')
    with op.batch_alter_table('token_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_activity_token'))
        batch_op.drop_index(batch_op.f('ix_token_activity_metric_type'))
        batch_op.drop_index('ix_token_activity_chain_token_metric_created_at')
        batch_op.drop_index(batch_op.f('ix_token_activity_chain'))

    op.drop_table('token_activity')
    with op.batch_alter_table('release', schema=None) as batch_op:
        batch_op.drop_index('ix_release_chain_created_at')
        batch_op.drop_index(batch_op.f('ix_release_chain'))

    op.drop_table('release')
    with op.batch_alter_table('governance_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_event_event_type'))
        batch_op.drop_index('ix_governance_event_chain_type_created_at')
        batch_op.drop_index(batch_op.f('ix_governance_event_chain'))

    op.drop_table('governance_event')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
